<h1>Ajout de post</h1>

<form action="?page=post_add" method="post">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Titre</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" name='title' placeholder="PutaClick's Title">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Contenu du post</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" name='content' rows="3"></textarea>
    </div>
    <div class="col-12">
        <button class="btn btn-info" type="submit">Valider</button>
    </div>

</form>